name: 'dataflix_transformations'
version: '1.0.0'
config-version: 2

profile: 'dataflix'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dataflix_transformations:
    staging:
      materialized: view
    marts:
      materialized: table
